about/urls.py
from django.urls import path
from .views import index

app_name = 'about'

urlpatterns = [
    path('', index, name='index')
]

blog/urls.py
from django.urls import path
from .views import index, article_list, article_detail

app_name = 'blog'

urlpatterns = [
    path('', index, name='index'),
    path('list/', article_list, name='list'),
    path('detail/<int:pk>/', article_detail, name='detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('about/', include('about.urls', namespace='about')),
    path('contact/', include('contact.urls', namespace='contact')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/urls.py
from django.urls import path
from .views import index

app_name = 'contact'

urlpatterns = [
    path('', index, name='index')
]

about/models.py
from django.db import models


class Feedback(models.Model):
    fullname = models.CharField(max_length=225)
    position = models.CharField(max_length=225)
    avatar = models.ImageField(upload_to='feedbacks/')
    message = models.TextField()

    def __str__(self):
        return self.fullname

blog/models.py
from django.db import models


class Category(models.Model):
    title = models.CharField(max_length=225)

    def __str__(self):
        return self.title


class Tag(models.Model):
    title = models.CharField(max_length=225)

    def __str__(self):
        return self.title


class Article(models.Model):
    author = models.ForeignKey("profile.Profile", on_delete=models.SET_NULL, null=True, blank=True)
    title = models.CharField(max_length=225)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='articles/')
    description = models.TextField()
    tags = models.ManyToManyField(Tag)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    author = models.ForeignKey("profile.Profile", on_delete=models.SET_NULL, null=True, blank=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    description = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        if self.author.user.get_full_name():
            return f"{self.author.user.get_full_name()}'s comment"
        return f"{self.author.user.username}'s comment"

    class Meta:
        ordering = ['-id']

contact/models.py
from django.db import models


class Contact(models.Model):
    name = models.CharField(max_length=225)
    email = models.EmailField()
    subject = models.CharField(max_length=225)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return self.name

profile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='authors/', null=True, blank=True)
    bio = models.TextField(null=True, blank=True)

    def __str__(self):
        if self.user.get_full_name() != '':
            return self.user.get_full_name()
        return self.user.username


def user_post_save(instance, sender, created, *args, **kwargs):
    if created:
        Profile.objects.create(user_id=instance.id)


post_save.connect(user_post_save, sender=User)

blog/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = '__all__'
        exclude = ['author', 'article']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['description'].widget.attrs.update({
            'class': "form-control",
            'id': 'message',
            'cols': 30,
            'rows': 3,
        })

contact/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, *kwargs)
        self.fields['name'].widget.attrs.update({
            "class": "form-control",
            "placeholder": 'Your Name'
        })
        self.fields['email'].widget.attrs.update({
            "class": "form-control",
            "placeholder": 'Email'
        })
        self.fields['subject'].widget.attrs.update({
            "class": "form-control",
            "placeholder": 'Subject'
        })
        self.fields['message'].widget.attrs.update({
            "class": "form-control",
            "placeholder": 'Message'
        })

about/views.py
from django.shortcuts import render
from .models import Feedback


def index(request):
    feedbacks = Feedback.objects.all()
    ctx = {
        'feedbacks': feedbacks
    }
    return render(request, 'readit/about.html', ctx)

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from .models import Article, Category, Tag, Comment
from .forms import CommentForm


def index(request):
    articles = Article.objects.order_by('-id')
    ctx = {
        'object_list': articles
    }
    return render(request, 'readit/index.html', ctx)


def article_list(request):
    articles = Article.objects.order_by('-id')
    cat = request.GET.get('cat')
    tag = request.GET.get('tag')
    search = request.GET.get('search')
    if search:
        articles = articles.filter(title__icontains=search)
    if cat:
        articles = articles.filter(category__title__exact=cat)
    if tag:
        articles = articles.filter(tags__title__exact=tag)
    ctx = {
        'object_list': articles
    }
    return render(request, 'readit/blog.html', ctx)


def article_detail(request, pk):
    article = get_object_or_404(Article, id=pk)
    categories = Category.objects.all()
    tags = Tag.objects.all()
    last_3_articles = Article.objects.order_by('-id')[:3]
    form = CommentForm()
    if request.method == 'POST':
        if not request.user.is_authenticated:
            return redirect(reverse('blog:detail', kwargs={'pk': pk}))
        form = CommentForm(data=request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.author_id = request.user.profile.id
            obj.article_id = article.id
            obj.save()
            return redirect(reverse('blog:detail', kwargs={'pk': pk}))

    ctx = {
        'object': article,
        'categories': categories,
        'tags': tags,
        'last_3_articles': last_3_articles,
        'form': form
    }
    return render(request, 'readit/blog-single.html', ctx)

contact/views.py
from django.shortcuts import render, redirect
from .forms import ContactForm
from django.contrib import messages


def index(request):
    form = ContactForm(request.POST or None)
    if form.is_valid():
        form.save()
        messages.success(request, 'Your message successfully sent')
        return redirect('contact:index')
    ctx = {
        'form': form
    }
    return render(request, 'readit/contact.html', ctx)

profile/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<!-- Mirrored from preview.colorlib.com/theme/readit/ by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 21 Jan 2023 14:45:55 GMT -->
<head>
    <title>Readit - Free Bootstrap 4 Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'css/aos.css' %}">
    <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script nonce="78c62ed7-5526-43ce-a52c-aa0caebccd63">
        (function(w,d){!function(f,g,h,i){f[h]=f[h]||{};f[h].executed=[];f.zaraz={deferred:[],listeners:[]};f.zaraz.q=[];f.zaraz._f=function(j){return function(){var k=Array.prototype.slice.call(arguments);f.zaraz.q.push({m:j,a:k})}};for(const l of["track","set","debug"])f.zaraz[l]=f.zaraz._f(l);f.zaraz.init=()=>{var m=g.getElementsByTagName(i)[0],n=g.createElement(i),o=g.getElementsByTagName("title")[0];o&&(f[h].t=g.getElementsByTagName("title")[0].text);f[h].x=Math.random();f[h].w=f.screen.width;f[h].h=f.screen.height;f[h].j=f.innerHeight;f[h].e=f.innerWidth;f[h].l=f.location.href;f[h].r=g.referrer;f[h].k=f.screen.colorDepth;f[h].n=g.characterSet;f[h].o=(new Date).getTimezoneOffset();if(f.dataLayer)for(const s of Object.entries(Object.entries(dataLayer).reduce(((t,u)=>({...t[1],...u[1]})))))zaraz.set(s[0],s[1],{scope:"page"});f[h].q=[];for(;f.zaraz.q.length;){const v=f.zaraz.q.shift();f[h].q.push(v)}n.defer=!0;for(const w of[localStorage,sessionStorage])Object.keys(w||{}).filter((y=>y.startsWith("_zaraz_"))).forEach((x=>{try{f[h]["z_"+x.slice(7)]=JSON.parse(w.getItem(x))}catch{f[h]["z_"+x.slice(7)]=w.getItem(x)}}));n.referrerPolicy="origin";n.src="https://preview.colorlib.com/cdn-cgi/zaraz/s.js?z="+btoa(encodeURIComponent(JSON.stringify(f[h])));m.parentNode.insertBefore(n,m)};["complete","interactive"].includes(g.readyState)?zaraz.init():f.addEventListener("DOMContentLoaded",zaraz.init)}(w,d,"zarazData","script");})(window,document);



    </script>
</head>
<body>
{% include 'navbar.html' %}
{% block content %}


{% endblock %}
{% include 'footer.html' %}

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/aos.js' %}"></script>
<script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
<script src="{% static 'js/scrollax.min.js' %}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&amp;sensor=false"></script>
<script src="{% static 'js/google-map.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');




</script>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/vaafb692b2aea4879b33c060e79fe94621666317369993"
        integrity="sha512-0ahDYl866UMhKuYcW078ScMalXqtFJggm7TmlUtp0UlD4eQk0Ixfnm5ykXKvGJNFjLMoortdseTfsRT8oCfgGA=="
        data-cf-beacon='{"rayId":"78d0d6187dc3fe4c","token":"cd0b4b3a733644fc843ef0b185f98241","version":"2022.11.3","si":100}'
        crossorigin="anonymous"></script>
</body>

<!-- Mirrored from preview.colorlib.com/theme/readit/ by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 21 Jan 2023 14:46:38 GMT -->
</html>

templates/footer.html
{% load static %}
<footer class="ftco-footer ftco-bg-dark ftco-section">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="logo"><a href="#">Read<span>it</span>.</a></h2>
                    <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there
                        live the blind texts.</p>
                    <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                        <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                        <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">latest News</h2>
                    <div class="block-21 mb-4 d-flex">
                        <a class="img mr-4 rounded" style="background-image: url({% static 'images/image_1.jpg' %});"></a>
                        <div class="text">
                            <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about</a></h3>
                            <div class="meta">
                                <div><a href="#"></span> Oct. 16, 2019</a></div>
                                <div><a href="#"></span> Admin</a></div>
                                <div><a href="#"></span> 19</a></div>
                            </div>
                        </div>
                    </div>
                    <div class="block-21 mb-4 d-flex">
                        <a class="img mr-4 rounded" style="background-image: url({% static 'images/image_2.jpg' %});"></a>
                        <div class="text">
                            <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about</a></h3>
                            <div class="meta">
                                <div><a href="#"></span> Oct. 16, 2019</a></div>
                                <div><a href="#"></span> Admin</a></div>
                                <div><a href="#"></span> 19</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4 ml-md-5">
                    <h2 class="ftco-heading-2">Information</h2>
                    <ul class="list-unstyled">
                        <li><a href="#" class="py-1 d-block"><span class="ion-ios-arrow-forward mr-3"></span>Home</a>
                        </li>
                        <li><a href="#" class="py-1 d-block"><span class="ion-ios-arrow-forward mr-3"></span>About</a>
                        </li>
                        <li><a href="#" class="py-1 d-block"><span
                                class="ion-ios-arrow-forward mr-3"></span>Articles</a></li>
                        <li><a href="#" class="py-1 d-block"><span class="ion-ios-arrow-forward mr-3"></span>Contact</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Have a Questions?</h2>
                    <div class="block-23 mb-3">
                        <ul>
                            <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span>
                            </li>
                            <li><a href="#"><span class="icon icon-phone"></span><span
                                    class="text">+2 392 3929 210</span></a></li>
                            <li><a href="#"><span class="icon icon-envelope"></span><span class="text"><span
                                    class="__cf_email__" data-cfemail="533a3d353c132a3c2621373c3e323a3d7d303c3e">[email&#160;protected]</span></span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">
                <p>
                    Copyright &copy;<script data-cfasync="false"
                                            src="https://preview.colorlib.com/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
                    <script>document.write(new Date().getFullYear());</script>
                    All rights reserved | This template is made with <i class="icon-heart color-danger"
                                                                        aria-hidden="true"></i> by <a
                        href="https://colorlib.com/" target="_blank">Colorlib</a>
                </p>
            </div>
        </div>
    </div>
</footer>

<div id="ftco-loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#F96D00"/>
    </svg>
</div>

templates/navbar.html
{% load static %}
<nav class="navbar px-md-0 navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
        <a class="navbar-brand" href="{% url 'blog:list' %}">Read<i>it</i>.</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav"
                aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="oi oi-menu"></span> Menu
        </button>
        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active"><a href="{% url 'blog:index' %}" class="nav-link">Home</a></li>
                <li class="nav-item"><a href="{% url 'blog:list' %}" class="nav-link">Articles</a></li>
                <li class="nav-item"><a href="{% url 'about:index' %}" class="nav-link">Team</a></li>
                <li class="nav-item"><a href="{% url 'contact:index' %}" class="nav-link">Contact</a></li>
            </ul>
        </div>
    </div>
</nav>

templates/readit/blog-single.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="hero-wrap hero-wrap-2 js-fullheight" style="background-image: url('{% static 'images/bg_1.jpg' %}');"
         data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate pb-5 text-center">
                <h1 class="mb-3 bread">Blog Single</h1>
                <p class="breadcrumbs"><span class="mr-2"><a href="index-2.html">Home <i
                        class="ion-ios-arrow-forward"></i></a></span> <span class="mr-2"><a href="blog.html">Blog <i
                        class="ion-ios-arrow-forward"></i></a></span> <span>Blog Single <i
                        class="ion-ios-arrow-forward"></i></span></p>
            </div>
        </div>
    </div>
</section>
<section class="ftco-section ftco-degree-bg">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 ftco-animate">
                <p class="mb-5">
                    <img src="{{ object.image.url }}" alt="" class="img-fluid">
                </p>
                <h2 class="mb-3">{{ object.title }}</h2>
                <p>{{ object.description|safe }}</p>
                <div class="tag-widget post-tag-container mb-5 mt-5">
                    <div class="tagcloud">
                        {% for tag in object.tags.all %}
                        <a href="{% url 'blog:list' %}?tag={{ tag.title }}#article_list" class="tag-cloud-link">{{ tag.title }}</a>
                        {% endfor %}
                    </div>
                </div>
                <div class="about-author d-flex p-4 bg-light">
                    {% if object.author.avatar %}
                    <div class="bio mr-5">
                        <img src="{{ object.author.avatar.url }}" alt="Image placeholder" style="width: 120px" class="img-fluid mb-4">
                    </div>
                    {% else %}
                    <div class="bio mr-5">
                        <img src="{% static 'images/user.png' %}" alt="Image placeholder" style="width: 120px" class="img-fluid mb-4">
                    </div>
                    {% endif %}
                    <div class="desc">
                        <h3>{{ object.author }}</h3>
                        {% if object.author.bio %}
                        <p>{{ object.author.bio }}</p>
                        {% endif %}
                    </div>
                </div>
                <div class="pt-5 mt-5" id="comments">
                    <h3 class="mb-5">{{ object.comment_set.count }} Comments</h3>
                    <ul class="comment-list">
                        {% for comment in object.comment_set.all %}
                        <li class="comment">
                            <div class="vcard bio">
                                {% if comment.author.avatar %}
                                <img src="{{ comment.author.avatar.url }}" style="width:60px" alt="Image placeholder">
                                {% else %}
                                <img src="{% static 'images/user.png' %}" style="width:60px" alt="Image placeholder">
                                {% endif %}
                            </div>
                            <div class="comment-body">
                                <h3>{{ comment.author }}</h3>
                                <div class="meta mb-3">{{ comment.created_date|date:'F d, Y' }} at {{ comment.created_date|date:'g:ia' }}</div>
                                <p>{{ comment.description }}</p>
                            </div>
                        </li>
                        {% endfor %}
                    </ul>

                    <div class="comment-form-wrap pt-5" >
                        <h3 class="mb-5">Leave a comment</h3>
                        <form method="post" action="#comments" class="p-5 bg-light">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="message">Message</label>
                                {{ form.description }}
                            </div>
                            <div class="form-group">
                                <input type="submit" value="Post Comment" class="btn py-3 px-4 btn-primary">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 sidebar pl-lg-5 ftco-animate">
                <div class="sidebar-box">
                    <form action="{% url 'blog:list' %}#article_list" class="search-form">
                        <div class="form-group">
                            <span class="icon icon-search"></span>
                            <input type="search" class="form-control" name="search" placeholder="Type a keyword and hit enter">
                        </div>
                    </form>
                </div>
                <div class="sidebar-box ftco-animate">
                    <div class="categories">
                        <h3>Categories</h3>
                        <ul>
                            {% for category in categories %}
                            <li><a href="{% url 'blog:list' %}?cat={{ category.title }}#article_list">{{ category.title }}<span class="ion-ios-arrow-forward"></span></a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div class="sidebar-box ftco-animate">
                    <h3>Recent Blog</h3>
                    {% for last_3 in last_3_articles %}
                    <div class="block-21 mb-4 d-flex">
                        <a class="blog-img mr-4" style="background-image: url({{ last_3.image.url }});"></a>
                        <div class="text">

                            <h3 class="heading"><a href="{% url 'blog:detail' last_3.id %}">{{ last_3.title }}</a></h3>
                            <div class="meta">
                                <div><a href="{% url 'blog:detail' last_3.id %}"><span class="icon-calendar"></span>{{ last_3.created_date|date:'F d, Y' }}</a></div>
                                <div><a href="{% url 'blog:detail' last_3.id %}"><span class="icon-person"></span>{{ last_3.author }}</a></div>
                                <div><a href="{% url 'blog:detail' last_3.id %}"><span class="icon-chat"></span> 19</a></div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <div class="sidebar-box ftco-animate">
                    <h3>Tag Cloud</h3>
                    <div class="tagcloud">
                        {% for tag in tags %}
                        <a href="{% url 'blog:list' %}?tag={{ tag.title }}#article_list" class="tag-cloud-link">{{ tag.title }}</a>
                        {% endfor %}
                    </div>
                </div>
                <div class="sidebar-box ftco-animate">
                    <h3>Paragraph</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus
                        voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur
                        similique, inventore eos fugit cupiditate numquam!</p>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/readit/blog.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="hero-wrap js-fullheight" style="background-image: url('{% static 'images/bg_1.jpg' %}');"
     data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-start"
             data-scrollax-parent="true">
            <div class="col-md-12 ftco-animate">
                <h2 class="subheading">Hello! Welcome to</h2>
                <h1 class="mb-4 mb-md-0">Readit blog</h1>
                <div class="row">
                    <div class="col-md-7">
                        <div class="text">
                            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia,
                                there live the blind texts. Separated they live in Bookmarksgrove right at the coast of
                                the Semantics, a large language ocean.</p>
                            <div class="mouse">
                                <a href="#" class="mouse-icon">
                                    <div class="mouse-wheel"><span class="ion-ios-arrow-round-down"></span></div>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<section class="ftco-section bg-light" id="article_list">
    <div class="container">

        <div class="row d-flex">
            {% for object in object_list %}
            <div class="col-md-4 d-flex ftco-animate">
                <div class="blog-entry justify-content-end">
                    <a href="{% url 'blog:detail' object.id %}" class="block-20" style="background-image: url('{{ object.image.url }}');">
                    </a>
                    <div class="text p-4 float-right d-block">
                        <div class="topper d-flex align-items-center">
                            <div class="one py-2 pl-3 pr-1 align-self-stretch">
                                <span class="day">{{ object.created_date|date:'d' }}</span>
                            </div>
                            <div class="two pl-0 pr-3 py-2 align-self-stretch">
                                <span class="yr">{{ object.created_date.year }}</span>
                                <span class="mos">{{ object.created_date|date:'F' }}</span>
                            </div>
                        </div>
                        <h3 class="heading mb-3"><a href="{% url 'blog:detail' object.id %}">{{ object.title }}</a></h3>
                        <span>{{ object.category }}</span>
                        <p>{{ object.description|safe|slice:120 }}...</p>
                        <p><a href="{% url 'blog:detail' object.id %}" class="btn-custom"><span class="ion-ios-arrow-round-forward mr-3"></span>Read
                            more</a></p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="row mt-5">
            <div class="col text-center">
                <div class="block-27">
                    <ul>
                        <li><a href="#">&lt;</a></li>
                        <li class="active"><span>1</span></li>
                        <li><a href="#">2</a></li>
                        <li><a href="#">3</a></li>
                        <li><a href="#">4</a></li>
                        <li><a href="#">5</a></li>
                        <li><a href="#">&gt;</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}